### ISSUE TITLE
Bump z-index

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/fedmenu#1]
I wonder if we want to bump the z-index or perhaps make it configurable.

Looking at the ambassador map, it seems OpenStreetMap is also using the z-index attribute and higher up than we are, thus hiding our menu.
http://fedoraproject.org/membership-map/ambassadors.html

**Comment by pypingou** [comment]
Bumping the z-index on `fedmenu-tray` makes the menu show up

**Comment by ralphbean** [comment]
Yeah, let's just bump it globally.  What did you bump it to?

**Comment by pypingou** [comment]
I bumped it to `1010` as OSM seems to use `1004`, but using 800 seems to work already

**Comment by ralphbean** [comment]
Fixed in 38e1997 (sorry, I accidentally pushed without a PR.  Will try not to do this again for this repo).
