### ISSUE TITLE
The menu shows up in screenshots

### ISSUE THREAD

**Issue by kparal** [fedora-infra/fedmenu#10]
If I create a page screenshot in Firefox, the menu shows up drawn over the screenshot:

![wiki](https://cloud.githubusercontent.com/assets/755451/7514612/5950ddba-f4bf-11e4-9284-8abddd3ff642.png)

Reproducer:
1. Start Firefox
2. Open https://fedoraproject.org/wiki/QA/Join
3. Open Developer Bar using Shift+F2 or via the menu (F10)
4. run `screenshot --fullpage wiki.png`
5. examine the screenshot

The fedmenu should stay absolutely hidden unless triggered, not just moved outside the screen viewport. Hope that's possible, I'm no HTML expert. Maybe just set css visiblity to 0?

**Comment by ralphbean** [comment]
We can probably solve this with the same way we can solve #11.  We currently just animate the menu off screen.. but if we actually remove it from the DOM (and then add it back later) then this shouldn't be an issue.
