### ISSUE TITLE
Searching on page finds strings on hidden fedmenu

### ISSUE THREAD

**Issue by schidlo** [fedora-infra/fedmenu#11]
I tried to find some string on fp wiki page (with ctrl+f) and some found occurrences wasn't highlighted (They won't show when I went through all by F3). I found out that the string I was searching for is in fedmenu, and when I opened it, it was highlighted. So searching tries to show found occurrences even on hidden fedmenu, which is confusing.

**Comment by ralphbean** [comment]
Wow.  Thanks for reporting this!  Can fix.

We'll have to actually add and remove the elements from the DOM instead of just hiding them.

**Comment by kparal** [comment]
Reproducer:
1. Open https://fedoraproject.org/wiki/QA/Join in Firefox
2. Search for `taskotron`
3. Firefox says there are 2 occurrences, and the first one is displayed, but the second one seems to be "nowhere". If you click on fedmenu icon, you'll realize that the second taskotron string is there. If you don't know that, it's confusing.
