### ISSUE TITLE
Links alignment

### ISSUE THREAD

**Issue by nask0** [fedora-infra/fedmenu#15]
I think that there is not enough space between text links.
Users cannot be quite sure what exactly they pressed if they not see url on browser status bar.d
![user-menu](https://cloud.githubusercontent.com/assets/248198/7863975/110d4494-0568-11e5-8e6b-00842dde739b.png)

Also, IMHO there is too much whitespace that can be utilized better.

**Comment by pypingou** [comment]
Which browser are you seeing? When hovering over the links I see the URL at the bottom of my Firefox window.

**Comment by ralphbean** [comment]
@nask0 for what it's worth, I agree.  I tried to use media queries to layout the window nicely for different browser sizes.. but they're not all perfect.

**Comment by nask0** [comment]
Browser: Chrome.
Yep i can see urls at bottom of my browser too, just think this is not user-friendly enough given that there is a so much white space :)

**Comment by ralphbean** [comment]
The changes in #16 factor into this.

**Comment by nask0** [comment]
I think we can close the issue.
