### ISSUE TITLE
Empty user menu on datagrepper

### ISSUE THREAD

**Issue by hroncok** [fedora-infra/fedmenu#3]
On https://apps.fedoraproject.org/datagrepper/raw?user=churchyard when I click my face, I see empty menu.

![dg](https://cloud.githubusercontent.com/assets/2401856/7416053/0f447e96-ef5d-11e4-82a7-9164f3d47115.png)

This is how it looks in other apps:

![pkgdb](https://cloud.githubusercontent.com/assets/2401856/7416062/1c65c2a6-ef5d-11e4-8625-69a2dd1d5089.png)

This might possibly be a Bootstrap issue.

**Comment by ralphbean** [comment]
Odd.  Your user menu shows up correctly for me on datagrepper:

![dg](https://cloud.githubusercontent.com/assets/331338/7416146/5685808e-ef2b-11e4-815c-bfa0e6a0e406.png)

That's firefox.  Let me try chrome.

**Comment by ralphbean** [comment]
Ah ha!  This is due to some CORS errors that chrome is hitting:

![cors-errors](https://cloud.githubusercontent.com/assets/331338/7416179/9abdc694-ef2b-11e4-824b-a773dbb322f0.png)
