### ISSUE TITLE
Reorder list to be user-focused

### ISSUE THREAD

**Issue by mattdm** [fedora-infra/fedmenu#4]
Right now, the list is of applications seems very internally-focused. I appreciate effort to better tie everything together, but I'm not sure right now who it's being tied together _for_.

Why, for example, might I want quick access to the GeoIP server? Or the github2fedmsg upstream? And In-development apps are listed _first_.

Maybe we could have Design Team look at the kind of information we'd like to present here?

**Comment by ralphbean** [comment]
Yup!  I sent it to [the list back when](https://lists.fedoraproject.org/pipermail/design-team/2015-February/007092.html).

**Comment by ralphbean** [comment]
Let's go for another couple iterations of feedback, definitely.

**Comment by mattdm** [comment]
Ah, thanks — I missed that. That explains the lower-right floater choice instead of a navbar. Doesn't look like the feedback went very deep into the contents presented, which is what I'm focusing on here.

**Comment by ralphbean** [comment]
Just [filed a design team ticket](https://fedorahosted.org/design-team/ticket/374) to initiate another discussion.

**Comment by ralphbean** [comment]
So, on the simplest level this has been dealt with in the production version.  The list was just re-ordered to put more reasonable stuff first.

Longer term, we'll be working with the design-team (**after** the launch of fedora-hubs) to revamp fedmenu to be a tighter place of domain integration.
