### ISSUE TITLE
Modal pulls up slowly

### ISSUE THREAD

**Issue by cydrobolt** [fedora-infra/fedmenu#5]
The modal seems a bit buggy in appearing.
I've worked with plenty of modals on my computer and they work fine, so it is not likely due to my computer's lag.

I'll take a look at this and see what can be done.

**Comment by ralphbean** [comment]
It seems to me it is only doing this in chrome, but it is snappy enough in Firefox.  Perhaps there needs to be some better vendor-prefixing in the css?

**Comment by cydrobolt** [comment]
Yeah, it actually seems to be pretty snappy in FF. In Chrome, though, it is slow to come up and produces grey stripes in the background.

**Comment by cydrobolt** [comment]
It also worked correctly in Chrome mobile.

**Comment by ralphbean** [comment]
I'm a little stuck on testing this / working on this until we can get chromium on F22.

**Comment by cydrobolt** [comment]
Chrome works for me on F22, I can probably take a look at this once I have time.

**Comment by ralphbean** [comment]
I just tried it in Chrome on F22 and it animates fine, no grey stripes.  Perhaps it was just a transient issue with whatever chrome release you were using at the time.  Please re-open if its still a problem!
